### ISSUE TITLE
Questions about SSE event handler.

### ISSUE THREAD

**Issue by ProximaB** [DaKaZ/esp8266-restclient#5]
Hi,
I'm wondering if server sent events (SSE), will be covered in this repository?
Thanks a lot for your work.

**Comment by DaKaZ** [comment]
Can you provide more detail, I am not familiar with SSE

**Comment by ProximaB** [comment]
Ok i will try to explain this.
Server sent events enable server to push data in real time to the client, especially browser. Its only one way connection. The case is that this is working via HTTP and doesn't need any special protocol implementation. Service using that can still be called restfull [[link](https://stackoverflow.com/questions/15749041/is-using-html5-server-sent-events-sse-restful)].
I'am working on my university project, and while developing it i came up that i will need frequen update my arduino using GET. 
I have idea that when client send GET request, server subscribe him to SSE, and client just listining for this event.
What do you think about it?

**Comment by DaKaZ** [comment]
It sounds like you are looking for Websockets or some other form of TCP based communication over HTTP.  That is really not the core purpose of this library, sorry.  This is just a simple library to fetch HTTP data from an SSL enabled server.
