### ISSUE TITLE
undefined reference to `RestClient::begin(unsigned char*)

### ISSUE THREAD

**Issue by derchirurg** [DaKaZ/esp8266-restclient#7]
Hi,

I get the following error when using (compiling with) the library:
undefined reference to `RestClient::begin(unsigned char*)

How can I fix it?

**Comment by DaKaZ** [comment]
Can you post any more code or a more complete stack trace?  I don't have enough information to answer your question.  Thanks

**Comment by derchirurg** [comment]
Stack:

Archiving built core (caching) in: C:\Users\mm\AppData\Local\Temp\arduino_cache_795941\core\core_esp8266_esp8266_d1_mini_CpuFrequency_80,UploadSpeed_921600,FlashSize_4M3M_ebde0b69c06017d77a526156b32cdc78.a
libraries\esp8266-restclient\RestClient.cpp.o: In function `RestClient::RestClient(char const*, int)':

D:\mm\Documents\Arduino\libraries\esp8266-restclient/RestClient.cpp:80: undefined reference to `RestClient::begin(unsigned char*)'

libraries\esp8266-restclient\RestClient.cpp.o: In function `RestClient::dhcp()':

D:\mm\Documents\Arduino\libraries\esp8266-restclient/RestClient.cpp:80: undefined reference to `RestClient::begin(unsigned char*)'

collect2.exe: error: ld returned 1 exit status

Mehrere Bibliotheken wurden für "Ethernet.h" gefunden
 Benutzt: C:\Users\mm\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.3.0\libraries\Ethernet
 Nicht benutzt: C:\Program Files (x86)\Arduino\libraries\Ethernet
exit status 1
Fehler beim Kompilieren für das Board WeMos D1 R2 & mini.

**Comment by derchirurg** [comment]
I think the issue is: RestClient.cpp does not implement begin(...)

**Comment by DaKaZ** [comment]
Can you check the contents of `D:\mm\Documents\Arduino\libraries\esp8266-restclient/RestClient.cpp` to make sure it matches this library's RestClient.cpp?  Our line 80 is very different than what your error is reporting.

**Comment by derchirurg** [comment]
If I check your RestClient.cpp at master branch, the method begin() is missing. So this cannot compile. I'm now using this lib: [](https://github.com/fabianofranca/ESP8266RestClient)

**Comment by ProximaB** [comment]
So first you're writing code then check if library working your way Nice.

**Comment by derchirurg** [comment]
Don't understand. The library does not compile at all. I just give it a try. I expected the lib will compile if it is checked in.

**Comment by DaKaZ** [comment]
Not sure there is anything that needs to be done here.  Please create a new issue if you need additional help.

Thanks
