### ISSUE TITLE
ESP32 - wifi.h

### ISSUE THREAD

**Issue by njordan77** [DaKaZ/esp8266-restclient#9]
Hi, i use your library successfully with ESP8266 for some months now...
Recently i had to switch to ESP32 due to performance issues on EpaperDisplays, now in general your library is based on esp8266wifi.h however ESP32 requires wifi.h which seems to be the new naming.....at least for ESP32. So I did change the library include in the header file of your code....no errors.....but also no output when i try to make a get on a restful server....which works well on ESP8266.

Any idea what needs to be considered on top in order to make it work with "wifi.h"?

Highly appreciate your thoughts and check. Regards Norbert

**Comment by njordan77** [comment]
hi, i still have not fixed this issue and i guess its rather easy for people familiar with this kind of code. Thanks for short feedback!!! Norbert

**Comment by ProximaB** [comment]
Hello @njordan77,
I think that the best what you can do in this situation is to rewrite this library by yourself. 
The code RestClient.cpp is only 343 lines of code. I bet you can do this step by step, and testing while making progress should bring you fully working rest client for ESP32.

I look up differences between those libraries and I think It might work just by replace it, but I see you've already done it, so the first thing I would try after that is debugging code using Serial.write.

I hope this helps. 
Regards, Bartek.

**Comment by DaKaZ** [comment]
Thanks for the response @ProximaB .  Alas I have not looked at the esp32 yet, sorry.  This client is specific to the edp8266
